services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    container_name: k8s-todo-frontend
    environment:
      TZ: "Asia/Tokyo"
      PORT: 4010
    ports:
      - "4010:4010"
    volumes:
      - type: bind
        source: ./frontend
        target: /app/frontend
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    container_name: k8s-todo-backend
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: todos
    ports:
      - "4020:4020"
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
    container_name: k8s-todo-db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
      - type: bind
        source: .docker/db/init.d
        target: /docker-entrypoint-initdb.d

volumes:
  mysqldata:
